apiVersion: batch/v1
kind: Job
metadata:
  name: data-importer
  namespace: bos-data-importer
spec:
  parallelism: 1    
  completions: 1
  backoffLimit: 1
  template:
    metadata:
      name: data-importer
    spec:
      volumes:
          - name: data-volume
            persistentVolumeClaim:
              claimName: data-pvc
          - name: di-script-volume
            configMap:
              name: data-importer-script
      containers:
      - name: data-importer
        image: data-importer-is:latest
        command: ["/app/start_app.sh"]
        volumeMounts:
            - mountPath: /data/
              name: data-volume
            - mountPath: /script/
              name: di-script-volume
      restartPolicy: Never
      activeDeadlineSeconds: 1800