kind: ConfigMap
apiVersion: v1
metadata:
  name: data-importer-script
  namespace: bos-data-importer
immutable: false
data:
  import_script.sh: |-
    #!/bin/bash
    sshpass -p 'Nalesniki22!' rsync --progress -avz -e ssh ksol@192.168.106.128:/test/ /data