kind: ConfigMap
apiVersion: v1
metadata:
  name: data-importer-script
  namespace: bos-data-importer
immutable: false
data:
  import_script.sh: |-
    #!/bin/bash
    rsync -a --password-file=/script/Nalesniki22! ksol@192.168.106.128:/test/ /data
  secretpass: |-
    Nalesniki22!
