apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: data-importer-bc
  namespace: bos-data-importer
spec:
  source:
    type: Git
    git:
      uri: https://github.com/JacobPCL/data-importer/  
    contextDir: app                    
    dockerfile: |-
      FROM registry.access.redhat.com/ubi8/ubi-minimal
      RUN microdnf -y install bash openssh-clients rsync grep
      WORKDIR /app
      COPY ./start_app.sh /app/start_app.sh
      RUN chmod a+rx /app/start_app.sh
  strategy:
    type: Docker
  output: 
    to:
      kind: ImageStreamTag
      name: data-importer-is:latest